<div class="websiteContents">
    <form method="post" action="../php/auth.php" class="form-login container">
        <h1 class="h3 mb-3 font-weight-normal">Sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" name="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me" name="rememberme"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit" style="background-color: #3f51b5">Sign in</button>
    </form>
</div>