<!--User page contents template-->
<div class="websiteContents">
    <a href="../php/logout.php" class="logout"> Log out</a>
    <div class="row">
        <div class="col-sm-2">
            <div class="person-circle text-center justify-content-md-center">
                <img src="../img/iron-man.jpg" alt="Person photo">
            </div>
        </div>
        <div class="col-sm-8">
            <div class="mypage-top-text">
                <div class="display-5 mb-1" id="person-name">Mr John Doe</div>
                <div class="lead mb-3">Status: Teacher</div>
                <div><Strong>About myself:</Strong>
                    Now this is the story all about how
                    My life got flipped, turned upside down
                    And I'd like to take a minute just sit right there
                    I'll tell you how I became the prince of a town called Bel-air
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <p id="contact-info">The longest street name you have ever seen 4444,Somewhere in America</p>
        </div>
    </div>
    <hr>
    <div class="mypage-bottom-info">
        <h3> Studies </h3>
        <p id="mypage-studies-content">
            1997-2000, Master of teacher, lego university
        </p>
        <hr>
        <h3> Experience </h3>
        <p id="mypage-experience-content">
            2000-2001, Policeman, Lego Police
        </p>
        <hr>
        <h3> Skills </h3>
        <p id="mypage-skill-content">
            Assembly programmer, linux user
        </p>
        <hr>
        <h3> Interests</h3>
        <p id="mypage-interests-content">
            Building models of houses
        </p>
    </div>
</div>